steps:

- name: 'gcr.io/cloud-builders/docker'
  id: BuildFunctions
  args: ['build', '-f', 'Dockerfile', '--tag=gcr.io/$PROJECT_ID/frontend', '.']

- name: 'gcr.io/$PROJECT_ID/frontend'
  id: DeployFrontend
  args: ['./deploy-hosting.sh', '$_FOLDER', '$_ENVIRONMENT', '$_PROJECT', '$_FIRE_TOKEN']
  waitFor:
  - BuildFunctions
