steps:

- name: 'gcr.io/cloud-builders/docker'
  id: BuildFunctions
  args: ['build', '-f', 'Dockerfile', '--tag=gcr.io/$PROJECT_ID/api', '.']

- name: 'gcr.io/$PROJECT_ID/api'
  id: TestFunctions
  args: ['./test-api.sh', '$_FOLDER', '$_ENVIRONMENT']
  waitFor:
  - BuildFunctions
